export type JoinStatus = "unresolved" | "matched" | "review" | "blocked";
export type SettlementResult = "PENDING" | "HIT" | "MISS" | "PUSH" | "REVIEW";
export type Side = "MORE" | "LESS";
export type PlayBucket = "safest" | "best_overall" | "upside";
export type OddsType = "goblin" | "standard" | "demon" | string;
export interface BoardSnapshot { id: string; source: string; actor_id: string | null; actor_run_id: string | null; dataset_id: string | null; sport: string; captured_at: string; created_at: string; }
export interface BoardProp { id: string; snapshot_id: string; projection_id: string; market_id: string | null; event_id: string | null; player_name: string; player_team: string | null; opponent_team: string | null; stat_type_raw: string; line: number | null; direction: string | null; odds_type: OddsType | null; start_time: string | null; board_time: string | null; updated_at: string | null; player_name_norm: string; player_team_norm: string | null; opponent_team_norm: string | null; stat_type_norm: string; join_status: JoinStatus; review_reason: string | null; raw: Record<string, unknown>; created_at: string; }
export interface RecommendationRun { id: string; snapshot_id: string | null; run_label: string | null; created_at: string; }
export interface RecommendationProp { id: string; recommendation_run_id: string; board_prop_id: string | null; projection_id: string; player_name: string; player_team: string | null; opponent_team: string | null; stat_type_norm: string; line: number; side: Side; odds_type: OddsType | null; confidence: number | null; edge: number | null; trust_score: number | null; play_bucket: PlayBucket | null; created_at: string; }
export interface Settlement { id: string; board_prop_id: string | null; recommendation_prop_id: string | null; projection_id: string; game_date: string | null; player_name: string; player_team: string | null; stat_type_norm: string; line: number; side: Side; actual_value: number | null; result: SettlementResult; closing_line: number | null; settled_at: string | null; notes: string | null; created_at: string; }
export interface ReviewQueueItem { id: string; board_prop_id: string | null; settlement_id: string | null; snapshot_id?: string | null; queue_type: string; reason: string; status: "open" | "resolved" | "ignored"; resolution: string | null; created_at: string; resolved_at: string | null; }
export interface ApifyPrizePicksRow { projection_id?: string | number; market_id?: string | number; event_id?: string | number; player_name?: string; name?: string; player?: string; player_team?: string; team?: string; opponent_team?: string; opponent?: string; stat_type?: string; stat?: string; line?: number | string; direction?: string | null; odds_type?: string | null; goblin_demon?: string | null; start_time?: string | null; game_start?: string | null; board_time?: string | null; updated_at?: string | null; [key: string]: unknown; }
